# ===================================================================
# Copyright © 2025 Sackey Ezekiel Etrue
# Distributed under the terms of the MIT license.
# ===================================================================

load("@rules_cc//cc:cc_library.bzl", "cc_library")
#===========================
# Build C++ Library        #
#===========================

cc_library(
	name = "mytoml",
	srcs = [
		"src/mytoml.cpp",
	],
	hdrs = glob(["include/mytoml/*.h", "include/mytoml/*.hpp"]),
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
)

#===========================
# Build C Library          #
#===========================

cc_library(
	name = "mytomlc",
	srcs = [
		"src/mytomlc.cpp",
	],
	hdrs = glob(["include/mytoml/*.h", "include/mytoml/*.hpp"]),
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
	deps = [":mytoml"],
)

# ===================================================================
