# ===================================================================
# Copyright © 2025 Sackey Ezekiel Etrue
# Distributed under the terms of the MIT license.
# ===================================================================

load("@rules_cc//cc:defs.bzl", "cc_test")

#===========================
# C++ Library Tests        #
#===========================

cc_test(
	name = "mytoml_test",
	srcs = ["cxx/Main.test.cpp"],
	deps = ["//:mytoml", "//tests/vendor/Catch2:catch2_main"],
)

#===========================
# C Library Tests          #
#===========================

cc_test(
	name = "mytomlc_test",
	srcs = ["c/Main.test.cpp"],
	deps = ["//:mytomlc", "//tests/vendor/Catch2:catch2_main"],
)

# ===================================================================
